import { createUseStyles } from 'react-jss';

const useDateTimeStyles = createUseStyles((theme: any) => ({
	rdtPicker: {
		width: 'fit-content',
		padding: '10px 10px',
		boxShadow: `0px 1px 10px 0px ${theme.colors.boxShadowColor}`,
		borderRadius: '8px',
		marginTop: '3px',
		position: 'absolute',
		backgroundColor: theme.colors.white,
		zIndex: 9,
	},
	dow: {
		textAlign: 'center',
		width: 'auto',
		borderBottom: 'none',
		padding: '9px 18px 5px',
	},
	rdtDays: { minWidth: '220px', margin: '0px' },
	rdtMonths: { margin: '0px' },
	rdtYears: { margin: '0px' },
	rdtDay: {
		padding: '4px 0px',
		width: 56,
		height: 30,
		display: 'flex',
		justifyContent: 'center',
		alignItems: 'center',
		cursor: 'pointer',
	},
	rdtOpen: { display: 'block' },
	rdtStatic: { boxShadow: 'none', position: 'static' },
	rdtTimeToggle: { textAlign: 'center' },
	rdtPickerTable: { width: '100%', margin: '0px 0px 5px 0px', borderSpacing: '0px 0px' },
	rdtPickerTd: { textAlign: 'center', height: 'auto', padding: '0px 12px' },
	rdtPickerTh: { textAlign: 'center', height: 'auto', padding: '5px 0px' },
	rdtOld: { color: theme.colors.neutralGray },
	rdtNew: { color: theme.colors.neutralGray },
	rdtToday: { position: 'relative', margin: '0px -12px 0px 12px' },
	rdtActive: {
		backgroundColor: theme.colors.gigaBlue1,
		color: theme.colors.white,
		borderRadius: 4,
	},
	rdtDisabled: {
		background: 'none',
		color: theme.colors.neutralGray,
		cursor: 'not-allowed',
		_hover: {
			background: 'none',
			color: theme.colors.neutralGray,
			cursor: 'not-allowed',
		},
	},
	rdtSwitch: {
		width: 'calc(100% - 20px)',
		borderBottom: `1px solid ${theme.colors.solitude}`,
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'center',
	},
	rdtNext: {
		fontSize: '0px',
		verticalAlign: 'bottom',
		width: 22,
		borderBottom: `1px solid ${theme.colors.solitude}`,
		marginRight: 15,
		paddingRight: 10,
	},
	rdtPrev: {
		marginLeft: 15,
		paddingLeft: 2,
		fontSize: '0px',
		width: 22,
		borderBottom: `1px solid ${theme.colors.solitude}`,
	},
	rdtPrevSpan: {
		display: 'block',
		cursor: 'pointer',
		padding: '2px 4px 0px',
		width: '18px',
		margin: '7px 0px',
	},
	rdtPickerTfoot: { borderTop: `1px solid ${theme.colors.solitude}` },
	rdtCounters: { display: 'flex' },
	rdtCounter: { width: '40px' },
	rdtCounterSeparator: { margin: '32px 0px' },
	rdtBtn: {
		lineHeight: '32px',
		cursor: 'pointer',
		width: '16px',
		padding: '4px 4px 0px',
		fontSize: '12px',
	},
	rdtCount: { height: '25px' },
	arrowDown: {
		verticalAlign: 'bottom',
		transform: 'rotate(315deg)',
		position: 'relative',
		left: '-4px',
		bottom: '-2px',
	},
	dispFlex: { display: 'flex', flexDirection: 'row' },
	inputDateIcon: {
		display: 'flex',
		position: 'relative',
		alignItems: 'center',
		justifyContent: 'center',
		padding: '0px 15px 0px 117px',
		cursor: 'pointer',
		marginLeft: '-149px',
	},
	inputTimeIcon: {
		display: 'flex',
		position: 'relative',
		alignItems: 'center',
		justifyContent: 'center',
		padding: '0px 15px 0px 100px',
		cursor: 'pointer',
		marginLeft: '-130px',
	},
	inputDateInput: {
		width: '145px',
		height: '30px',
		borderRadius: '3px !important',
	},
	inputTimeInput: {
		width: '130px',
		height: '30px',
		borderRadius: '3px !important',
	},
	snmpAuthSwitch: {
		paddingRight: '16px',
	},
	displayGrid: {
		display: 'grid',
		margin: '0px 2px',
	},
}));

export default useDateTimeStyles;
