import { createUseStyles } from 'react-jss';

const Styles = createUseStyles((theme: any) => ({
	tableBottom: {
		flexShrink: '0',
		width: '100%',
		height: '36px',
		display: 'flex',
		flexDirection: 'row',
		justifyContent: 'flex-start',
		alignItems: 'center',
		overflow: 'visible',
		margin: '8px 0px 12px 0px',
		boxSizing: 'border-box',
	},
	pagination: {
		boxSizing: 'border-box',
		flexShrink: '0',
		height: '36px',
		display: 'flex',
		flexDirection: 'row',
		justifyContent: 'flex-start',
		alignItems: 'center',
		padding: '0px 6px 2px 6px',
		overflow: 'visible',
		borderRadius: '32px',
		border: `3px solid ${theme.colors.gigaGrey1}`,
		margin: '-6px 24px -3px 0px',
	},
	paginatorButton: {
		flexShrink: '0',
		width: '52px',
		height: '26px',
		display: 'flex',
		flexDirection: 'row',
		justifyContent: 'center',
		alignItems: 'center',
		overflow: 'visible',
		borderRadius: '4px',
		background: 'none',
		margin: '5px 3px',
		border: 'none !important',
		paddingTop: '4px',
	},
	paginatorSeparator: {
		flexShrink: '0',
		width: '2px',
		height: '24px',
		backgroundColor: theme.colors.gigaGrey1,
		overflow: 'visible',
	},
	paginatorText: {
		flexShrink: '0',
		// height: '36px',
		whiteSpace: 'pre',
		overflow: 'visible',
		fontWeight: '400',
		fontStyle: 'normal',
		fontFamily: '"Nunito Sans", sans-serif',
		color: theme.colors.gigaGrey2,
		fontSize: '14px',
		letterSpacing: '0px',
		lineHeight: '1.6',
		padding: '8px 7px 5px 4px',
	},
	txtPageInput: {
		boxSizing: 'border-box',
		width: '36px',
		height: '22px',
		flexDirection: 'row',
		justifyContent: 'flex-start',
		alignItems: 'center',
		backgroundColor: theme.colors.gigaGrey1,
		overflow: 'visible',
		borderRadius: '6px',
		fontWeight: '400',
		fontStyle: 'normal',
		fontFamily: 'Nunito Sans, sans-serif',
		color: theme.colors.gigaGrey3,
		fontSize: '14px',
		textAlign: 'center',
		border: 'none',
		display: 'inline',
		padding: '0px !important',
		mozAppearance: 'textfield',
		'&::-webkit-outer-spin-button': {
			webkitAppearance: 'none',
		},
		'&::-webkit-inner-spin-button': {
			webkitAppearance: 'none',
		},
	},
	paginatorCountText: {
		flexShrink: '0',
		width: '72px',
		height: '22px',
		whiteSpace: 'pre',
	},
	rowMetadata: {
		overflow: 'visible',
		fontWeight: '400',
		fontStyle: 'normal',
		fontFamily: 'Nunito Sans, sans-serif',
		color: theme.colors.gigaGrey2,
		fontSize: '14px',
		letterSpacing: '0px',
		lineHeight: '1.6',
	},
	disabledIcon: {
		opacity: '0.5',
	},
	displayFlex: {
		display: 'flex',
	},
	pt7: {
		paddingTop: '7px',
	},
}));

export default Styles;
