import { createUseStyles } from 'react-jss';

const Styles = createUseStyles((theme: any) => ({
	headerCell: {
		color: '#63737B',
		backgroundColor: '#edf2f5',
		borderRight: `3px solid ${theme.colors.white} !important`,
		fontWeight: 'bolder',
		fontSize: '14px',
		letterSpacing: '0px',
		lineHeight: '24px',
		overflow: 'hidden',
		whiteSpace: 'nowrap',
		textOverflow: 'ellipsis',
		padding: '0 !important',
		'&:last-child': {
			backgroundColor: `${theme.colors.white} !important`,
			'& button': {
				boxShadow: 'none',
				color: 'inherit',
				backgroundImage: 'none',
			},
			'& $headerContent': {
				borderRadius: `0px 8px 0px 0px`,
				height: `100%`,
				alignItems: `flex-start`,
				paddingTop: `6px`,
			},
		},
		'&:first-child': {
			borderRadius: '8px 0px 0px 0px',
		},
	},
	headerContentEllipsis: {
		textOverflow: 'ellipsis',
		overflow: 'hidden',
		whiteSpace: 'nowrap',
	},
	headerMenu: {
		backgroundColor: theme.colors.gigaGrey1,
		borderRight: `3px solid ${theme.colors.white}`,
		zIndex: '5 !important',
		overflow: 'visible',
		position: 'absolute',
	},
	headerContent: {
		boxSizing: 'border-box',
		height: '36px',
		display: 'flex',
		flexDirection: 'row',
		justifyContent: 'flex-start',
		alignItems: 'center',
		padding: '0px 8px 0px 20px',
		overflow: 'visible',
		width: 'auto !important',
		'&:last-child': {
			padding: '0px 8px 0px 8px',
		},
	},
	headerContentData: {
		backgroundColor: theme.colors.gigaGrey1,
		flexShrink: '0',
		whiteSpace: 'pre',
		overflow: 'visible',
		fontWeight: '800',
		fontStyle: 'normal',
		fontFamily: 'Nunito Sans, sans-serif',
		color: '#6c737b',
		fontSize: '14px',
		letterSpacing: '0px',
		lineHeight: '1.2',
		textAlign: 'left',
	},
	overflowVisible: {
		overflow: 'visible !important',
	},
	resizer: {
		right: '0',
		width: '10px !important',
		height: '100%',
		position: 'absolute',
		top: '0',
		zIndex: '1',
		touchAction: 'none',
	},
	sortIcon: {
		display: 'inline-block',
		verticalAlign: 'middle',
		color: theme.colors.colorNeutral8,
		boxSizing: 'border-box',
		minWidth: '7px',
		width: '7px',
		height: '7px',
		borderWidth: '1px 1px 0 0',
		borderStyle: 'solid',
		alignItems: 'center',
		marginLeft: 'auto',
		top: '14px',
		bottom: '0',
		right: '10px',
		'&::before': {
			content: "''",
			boxSizing: 'border-box',
			right: '0',
			top: '-1px',
			position: 'absolute',
			height: '1px',
			boxShadow: 'inset 0 0 0 32px',
			width: '9px',
			transform: 'rotate(-45deg)',
			transformOrigin: 'right top',
		},
	},
	ascSortIcon: {
		transform: 'rotate(-45deg)',
	},
	descSortIcon: {
		transform: 'rotate(135deg)',
	},
	filterGroup: {
		padding: '0px 12px 6px 12px',
	},
}));

export default Styles;
