import { useCustomTheme } from '../../../commons';
import { createUseStyles } from 'react-jss';
import { getThemingStyles } from '../../../utils/utils';
const AccordianStyles = function () {
	const theme = useCustomTheme();
	// Get the component style object from the theme
	const themingStyles = getThemingStyles(theme, `components.Accordian`) || {};
	const useStyles = createUseStyles({
		accordion: {
			transition: '0.4s',
			width: '100%',
		},
		head: {
			width: '100%',
			boxSizing: 'border-box',
			height: '59px' /* 59px */,
			display: 'flex',
			flexDirection: 'row',
			justifyContent: 'flex-start',
			alignItems: 'center',
			padding: '14px 16px',
			backgroundColor: themingStyles.baseStyle.backgroundColor,
			overflow: 'visible',
			borderColor: themingStyles.baseStyle.borderColor,
			borderStyle: 'solid',
			borderTopWidth: 1,
			borderLeftWidth: 0,
			borderRightWidth: 0,
		},
		stackGroup: {
			flexShrink: 0,
			width: 'auto' /* 209px */,
			height: 'auto' /* 27px */,
			display: 'flex',
			flexDirection: 'row',
			justifyContent: 'flex-start',
			alignItems: 'center',
			overflow: 'visible',
			color: themingStyles.baseStyle.color,
		},
		stackGroupLabel: {
			flexShrink: 0,
			width: 'auto' /* 153px */,
			height: 'auto' /* 19px */,
			fontWeight: 700,
			fontStyle: 'normal',
			fontFamily: `"Nunito Sans", sans-serif`,
			color: themingStyles.baseStyle.color,
			fontSize: 16,
			letterSpacing: 0,
			lineHeight: 1.2,
			textAlign: 'left',
			padding: '2px 8px',
		},
		body: {
			maxHeight: 0,
			transition: '200ms ease-in-out',
		},
		focusedBody: {
			padding: '0 8px',
			maxHeight: 0,
			transition: '200ms ease-in-out',
			boxSizing: 'border-box',
			width: 'auto',
			height: 'auto' /* 212px */,
			display: 'flex',
			flexDirection: 'row',
			justifyContent: 'flex-start',
			alignItems: 'center',
			boxShadow: 'inset 0px 0px 0px 3px rgba(90, 155, 255, 0.1)',
			backgroundColor: '#ffffff',
			border: `1px solid transparent`,
			borderColor: themingStyles.focusStyle.borderColor,
		},
		activeBody: {
			maxHeight: '212px',
			boxSizing: 'border-box',
			flexShrink: 0,
			width: 'auto',
			height: 'auto' /* 212px */,
			display: 'flex',
			flexDirection: 'column',
			justifyContent: 'flex-start',
			alignItems: 'flex-start',
			padding: 8,
			backgroundColor: '#fff',
		},
		searchInputText: {
			flexShrink: 0,
			width: 'auto' /* 91px */,
			height: 'auto' /* 16px */,
			whiteSpace: 'pre',
			overflow: 'visible',
			fontWeight: 400,
			fontStyle: 'normal',
			fontFamily: `"Nunito Sans", sans-serif`,
			color: '#8a919a',
			fontSize: 16,
			letterSpacing: 0,
			lineHeight: 1,
			textAlign: 'left',
			marginLeft: 'auto',
			'& input': {
				borderBottom: 0,
			},
		},
		searchInput: {
			border: 'none',
			boxShadow: 'none',
			backgroundColor: themingStyles.baseStyle.backgroundColor,
			color: '#8a919a',
			textAlign: 'right',
			fontSize: 16,
			'&:focus': {
				border: 'none',
				boxShadow: 'none',
				outline: 'none',
			},
		},
		clearTextIcon: {
			flexShrink: 0,
			width: 16,
			height: 16,
			backgroundColor: '#bbc2c9',
			overflow: 'visible',
			borderRadius: 16,
			paddingTop: '4px',
			paddingLeft: '4px',
			marginTop: '10px',
		},
		itemsMatchString: {
			flexShrink: 0,
			width: 'auto' /* 156px */,
			height: 'auto' /* 20px */,
			whiteSpace: 'pre',
			overflow: 'visible',
			fontWeight: 400,
			fontStyle: 'normal',
			fontFamily: `"Nunito Sans", sans-serif`,
			color: `#8a919a`,
			fontSize: 16,
			letterSpacing: 0,
			lineHeight: 1.2,
			padding: '8px',
		},
		accButton: {
			padding: 0,
			borderRadius: 0,
			color: 'inherit',
			minWidth: '24px',
			height: '24px',
			border: '1px solid transparent',
			WebkitFilter: 'initial',
			'&:hover': {
				color: 'inherit !important',
				textDecoration: 'none !important',
			},
			'&:focus-visible': {
				borderColor: themingStyles.focusStyle.borderColor,
				outline: 'none',
				boxShadow: 'inset 0px 0px 0px 3px rgba(90, 155, 255, 0.1)',
			},
		},
	});
	return useStyles();
};
const InternalStyles = function () {
	return {};
};
export default { InternalStyles, AccordianStyles };
