import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import Table from '../components/Table/Table';

export default {
	title: 'Table',
	component: Table,
	argTypes: {},
} as ComponentMeta<typeof Table>;

//👇 We create a “template” of how args map to rendering
const Template: ComponentStory<typeof Table> = (args) => (
	<div style={{ height: '700px' }}>
		<Table {...args} />
	</div>
);

export const Default = Template.bind({});

Default.args = {
	columns: [
		{
			Header: 'First Name',
			accessor: 'firstName',
		},
		{
			Header: 'Last Name',
			accessor: 'lastName',
		},
		{
			Header: 'Age',
			accessor: 'age',
		},
		{
			Header: 'Visits',
			accessor: 'visits',
		},
		{
			Header: 'Status',
			accessor: 'status',
		},
		{
			Header: 'Profile Progress',
			accessor: 'progress',
		},
	],
	data: [
		{ firstName: 'maintenance', lastName: 'lumber', age: 19, visits: 57, progress: 50, status: 'relationship' },
		{ firstName: 'flock', lastName: 'sneeze', age: 3, visits: 74, progress: 5, status: 'relationship' },
		{ firstName: 'discussion', lastName: 'proposal', age: 27, visits: 40, progress: 13, status: 'relationship' },
		{ firstName: 'teacher', lastName: 'mice', age: 7, visits: 24, progress: 84, status: 'single' },
		{ firstName: 'literature', lastName: 'toy', age: 27, visits: 97, progress: 44, status: 'single' },
		{ firstName: 'currency', lastName: 'clothes', age: 24, visits: 97, progress: 61, status: 'relationship' },
		{ firstName: 'weakness', lastName: 'sky', age: 13, visits: 54, progress: 72, status: 'single' },
		{ firstName: 'cloud', lastName: 'friction', age: 5, visits: 91, progress: 92, status: 'single' },
		{ firstName: 'volume', lastName: 'plants', age: 16, visits: 47, progress: 80, status: 'single' },
		{ firstName: 'cakes', lastName: 'buyer', age: 18, visits: 95, progress: 56, status: 'complicated' },
		{ firstName: 'egg', lastName: 'argument', age: 22, visits: 43, progress: 65, status: 'relationship' },
		{ firstName: 'teeth', lastName: 'opportunity', age: 29, visits: 55, progress: 44, status: 'single' },
		{ firstName: 'opportunity', lastName: 'bike', age: 17, visits: 23, progress: 0, status: 'complicated' },
		{ firstName: 'currency', lastName: 'needle', age: 27, visits: 40, progress: 84, status: 'complicated' },
		{ firstName: 'process', lastName: 'afterthought', age: 13, visits: 19, progress: 71, status: 'relationship' },
		{ firstName: 'spot', lastName: 'roll', age: 17, visits: 14, progress: 73, status: 'relationship' },
		{ firstName: 'air', lastName: 'partner', age: 26, visits: 7, progress: 47, status: 'complicated' },
		{ firstName: 'self', lastName: 'water', age: 17, visits: 32, progress: 90, status: 'complicated' },
		{ firstName: 'refrigerator', lastName: 'mom', age: 16, visits: 97, progress: 59, status: 'relationship' },
		{ firstName: 'opportunity', lastName: 'coal', age: 4, visits: 81, progress: 98, status: 'single' },
		{ firstName: 'donkey', lastName: 'porter', age: 12, visits: 87, progress: 11, status: 'complicated' },
		{ firstName: 'cars', lastName: 'wren', age: 16, visits: 34, progress: 1, status: 'complicated' },
		{ firstName: 'honey', lastName: 'cats', age: 12, visits: 73, progress: 44, status: 'complicated' },
		{ firstName: 'powder', lastName: 'box', age: 3, visits: 22, progress: 65, status: 'single' },
		{ firstName: 'thunder', lastName: 'territory', age: 8, visits: 91, progress: 64, status: 'relationship' },
		{ firstName: 'ad', lastName: 'comparison', age: 4, visits: 59, progress: 19, status: 'single' },
		{ firstName: 'box', lastName: 'performance', age: 22, visits: 25, progress: 12, status: 'single' },
		{ firstName: 'extent', lastName: 'history', age: 17, visits: 63, progress: 94, status: 'complicated' },
		{ firstName: 'penalty', lastName: 'shame', age: 16, visits: 43, progress: 56, status: 'single' },
		{ firstName: 'database', lastName: 'kittens', age: 10, visits: 38, progress: 82, status: 'single' },
		{ firstName: 'chemistry', lastName: 'moment', age: 18, visits: 11, progress: 45, status: 'complicated' },
		{ firstName: 'jeans', lastName: 'aftermath', age: 25, visits: 8, progress: 75, status: 'relationship' },
		{ firstName: 'plastic', lastName: 'girl', age: 15, visits: 65, progress: 51, status: 'relationship' },
		{ firstName: 'skill', lastName: 'promotion', age: 4, visits: 56, progress: 43, status: 'single' },
		{ firstName: 'daughter', lastName: 'toe', age: 18, visits: 86, progress: 70, status: 'relationship' },
		{ firstName: 'drop', lastName: 'lamp', age: 3, visits: 63, progress: 0, status: 'relationship' },
		{ firstName: 'produce', lastName: 'place', age: 21, visits: 49, progress: 78, status: 'complicated' },
		{ firstName: 'zipper', lastName: 'cub', age: 19, visits: 98, progress: 76, status: 'complicated' },
		{ firstName: 'noise', lastName: 'perception', age: 0, visits: 30, progress: 38, status: 'complicated' },
		{ firstName: 'wool', lastName: 'stone', age: 27, visits: 90, progress: 83, status: 'relationship' },
		{ firstName: 'copy', lastName: 'profit', age: 9, visits: 90, progress: 62, status: 'complicated' },
		{ firstName: 'entry', lastName: 'tin', age: 3, visits: 2, progress: 92, status: 'single' },
		{ firstName: 'substance', lastName: 'knot', age: 4, visits: 30, progress: 2, status: 'single' },
		{ firstName: 'tray', lastName: 'minute', age: 13, visits: 21, progress: 80, status: 'relationship' },
		{ firstName: 'rabbits', lastName: 'bucket', age: 18, visits: 80, progress: 68, status: 'complicated' },
		{ firstName: 'butter', lastName: 'elbow', age: 0, visits: 52, progress: 85, status: 'single' },
		{ firstName: 'significance', lastName: 'cable', age: 8, visits: 97, progress: 45, status: 'relationship' },
		{ firstName: 'prison', lastName: 'carriage', age: 9, visits: 54, progress: 48, status: 'single' },
		{ firstName: 'match', lastName: 'reward', age: 1, visits: 83, progress: 96, status: 'relationship' },
		{ firstName: 'gate', lastName: 'perception', age: 22, visits: 61, progress: 4, status: 'relationship' },
		{ firstName: 'answer', lastName: 'perception', age: 27, visits: 49, progress: 51, status: 'complicated' },
		{ firstName: 'boot', lastName: 'crow', age: 15, visits: 89, progress: 35, status: 'complicated' },
		{ firstName: 'writer', lastName: 'audience', age: 0, visits: 49, progress: 13, status: 'single' },
		{ firstName: 'bottle', lastName: 'country', age: 16, visits: 32, progress: 77, status: 'complicated' },
		{ firstName: 'personality', lastName: 'year', age: 4, visits: 94, progress: 52, status: 'relationship' },
		{ firstName: 'goldfish', lastName: 'creator', age: 28, visits: 69, progress: 84, status: 'single' },
		{ firstName: 'media', lastName: 'light', age: 12, visits: 29, progress: 38, status: 'single' },
		{ firstName: 'patch', lastName: 'mind', age: 27, visits: 76, progress: 29, status: 'complicated' },
		{ firstName: 'blow', lastName: 'movie', age: 25, visits: 30, progress: 50, status: 'complicated' },
		{ firstName: 'extent', lastName: 'fowl', age: 19, visits: 75, progress: 92, status: 'complicated' },
		{ firstName: 'stretch', lastName: 'rainstorm', age: 3, visits: 65, progress: 92, status: 'relationship' },
		{ firstName: 'scarf', lastName: 'iron', age: 18, visits: 56, progress: 58, status: 'single' },
		{ firstName: 'equipment', lastName: 'fire', age: 20, visits: 55, progress: 97, status: 'relationship' },
		{ firstName: 'water', lastName: 'border', age: 19, visits: 71, progress: 62, status: 'relationship' },
		{ firstName: 'society', lastName: 'need', age: 21, visits: 14, progress: 43, status: 'single' },
		{ firstName: 'clocks', lastName: 'mode', age: 16, visits: 88, progress: 84, status: 'complicated' },
		{ firstName: 'stranger', lastName: 'coach', age: 21, visits: 98, progress: 42, status: 'single' },
		{ firstName: 'fall', lastName: 'addition', age: 4, visits: 72, progress: 84, status: 'single' },
		{ firstName: 'ornament', lastName: 'shoe', age: 17, visits: 95, progress: 7, status: 'relationship' },
		{ firstName: 'toe', lastName: 'rock', age: 15, visits: 84, progress: 51, status: 'complicated' },
		{ firstName: 'test', lastName: 'stamp', age: 13, visits: 7, progress: 84, status: 'complicated' },
		{ firstName: 'brain', lastName: 'hour', age: 10, visits: 31, progress: 20, status: 'single' },
		{ firstName: 'employee', lastName: 'thing', age: 18, visits: 63, progress: 16, status: 'relationship' },
		{ firstName: 'zebra', lastName: 'bath', age: 12, visits: 90, progress: 45, status: 'single' },
		{ firstName: 'importance', lastName: 'weakness', age: 5, visits: 66, progress: 98, status: 'complicated' },
		{ firstName: 'republic', lastName: 'touch', age: 13, visits: 64, progress: 14, status: 'single' },
		{ firstName: 'glass', lastName: 'mouth', age: 22, visits: 25, progress: 75, status: 'relationship' },
		{ firstName: 'steak', lastName: 'aunt', age: 15, visits: 35, progress: 50, status: 'complicated' },
		{ firstName: 'comb', lastName: 'station', age: 17, visits: 62, progress: 43, status: 'relationship' },
		{ firstName: 'sock', lastName: 'spring', age: 10, visits: 43, progress: 42, status: 'single' },
		{ firstName: 'road', lastName: 'guidance', age: 4, visits: 65, progress: 59, status: 'complicated' },
		{ firstName: 'chance', lastName: 'flock', age: 24, visits: 77, progress: 96, status: 'single' },
		{ firstName: 'soda', lastName: 'guitar', age: 19, visits: 78, progress: 39, status: 'complicated' },
		{ firstName: 'homework', lastName: 'ladybug', age: 15, visits: 36, progress: 37, status: 'single' },
		{ firstName: 'trousers', lastName: 'bead', age: 24, visits: 21, progress: 39, status: 'complicated' },
		{ firstName: 'midnight', lastName: 'detail', age: 16, visits: 2, progress: 77, status: 'complicated' },
		{ firstName: 'vein', lastName: 'aspect', age: 7, visits: 47, progress: 50, status: 'complicated' },
		{ firstName: 'afternoon', lastName: 'climate', age: 15, visits: 44, progress: 12, status: 'complicated' },
		{ firstName: 'question', lastName: 'idea', age: 21, visits: 68, progress: 29, status: 'relationship' },
		{ firstName: 'highway', lastName: 'childhood', age: 10, visits: 52, progress: 78, status: 'single' },
		{ firstName: 'safety', lastName: 'pleasure', age: 23, visits: 49, progress: 71, status: 'complicated' },
		{ firstName: 'journey', lastName: 'animal', age: 24, visits: 24, progress: 56, status: 'complicated' },
		{ firstName: 'safety', lastName: 'basin', age: 4, visits: 19, progress: 10, status: 'single' },
		{ firstName: 'boyfriend', lastName: 'verse', age: 9, visits: 35, progress: 17, status: 'relationship' },
		{ firstName: 'comb', lastName: 'game', age: 17, visits: 9, progress: 51, status: 'relationship' },
		{ firstName: 'order', lastName: 'obligation', age: 7, visits: 28, progress: 59, status: 'complicated' },
		{ firstName: 'weight', lastName: 'dock', age: 15, visits: 77, progress: 76, status: 'relationship' },
		{ firstName: 'food', lastName: 'gate', age: 16, visits: 53, progress: 45, status: 'relationship' },
		{ firstName: 'contract', lastName: 'play', age: 6, visits: 11, progress: 63, status: 'single' },
		{ firstName: 'currency', lastName: 'window', age: 3, visits: 81, progress: 15, status: 'relationship' },
	],
};
