import { createUseStyles } from 'react-jss';

const Styles = createUseStyles((theme: any) => ({
	gigaTable: {
		display: 'block',
		overflow: 'auto',
		height: '100%',
		width: 'calc(100% + 28px)',
		marginLeft: '-14px',
		position: 'relative',
	},
	tableHeader: {
		display: `block`,
		boxSizing: 'border-box',
		flex: '0 0 auto',
		position: 'sticky',
		zIndex: 6,
		top: 0,
	},
	tableBody: {},
	table: {
		width: '100%',
		height: 'calc(100% - 60px)',
		marginBottom: '0px',
		display: `flex`,
		flexDirection: `column`,
		overflow: 'auto',
	},
	toggleArrow: {
		cursor: 'pointer',
		userSelect: 'none',
		marginLeft: '25px !important',
		paddingTop: '4px !important',
		paddingBottom: '4px !important',
		textIndent: '20px',
		'&:before': {
			borderStyle: 'solid',
			borderWidth: '0.05em 0.05em 0 0',
			display: 'inline-block',
			height: '8px',
			content: '""',
			position: 'relative',
			top: '4px',
			left: '-10px',
			transform: 'rotate(135deg)',
			verticalAlign: 'top',
			width: '8px',
			marginLeft: '-8px',
		},
	},
	toggleArrowDown: {
		cursor: 'pointer',
		userSelect: 'none',
		marginLeft: '25px !important',
		paddingTop: '4px !important',
		paddingBottom: '4px !important',
		textIndent: '20px',
		'&:before': {
			borderStyle: 'solid',
			borderWidth: '0.05em 0.05em 0 0',
			display: 'inline-block',
			height: '8px',
			content: '""',
			position: 'relative',
			top: '6px',
			left: '-10px',
			transform: 'rotate(45deg)',
			verticalAlign: 'top',
			width: '8px',
			marginLeft: '-8px',
		},
	},
}));

export default Styles;
