import { createUseStyles } from 'react-jss';

const Styles = createUseStyles((theme: any) => ({
	customizingFlyingMenu: {
		display: 'block',
		position: 'absolute',
		zIndex: '1000',
		left: '-262px',
		width: '292px',
		maxHeight: '453px',
		fontWeight: 'bolder',
		borderRadius: '8px',
		listStyle: 'none',
		flexDirection: 'column',
		justifyContent: 'flex-start',
		alignItems: 'flex-start',
		boxShadow: '0px 1px 10px 0px rgba(0, 0, 0, 0.15)',
		backgroundColor: '#ffffff',
		overflow: 'auto',
		padding: '0px',
		marginTop: '8px',
	},
	flyingMenuHeader: {
		boxSizing: 'border-box',
		flexShrink: '0',
		width: '100%',
		height: '50px',
		display: 'flex',
		flexDirection: 'row',
		justifyContent: 'space-between',
		alignItems: 'center',
		padding: '7px 16px 7px 16px',
		backgroundColor: '#f9fbfc',
		overflow: 'visible',
		borderColor: '#edf2f5',
		borderStyle: 'solid',
		fontSize: '16px',
		borderTopWidth: '0px',
		borderBottomWidth: '1px',
		borderLeftWidth: '0px',
		borderRightWidth: '0px',
	},
	floatRight: {
		float: 'right !important',
	},
	flyingMenuItemStack: {
		padding: '8px 8px 4px',
	},
	customizeSettings: {
		borderRadius: '10px',
		padding: '0px',
		minWidth: '24px',
		height: '24px',
	},
	flyingMenuItem: {
		boxSizing: 'border-box',
		flexShrink: '0',
		width: '100%',
		fontSize: '16px',
		height: '36px',
		display: 'flex',
		flexDirection: 'row',
		justifyContent: 'flex-start',
		alignItems: 'center',
		padding: '6px 8px 6px 8px',
		overflow: 'auto',
		borderRadius: '4px',
	},
}));

export default Styles;
