import { createUseStyles } from 'react-jss';

const QuickViewStyles = createUseStyles({
	drawer: {
		position: 'fixed',
		height: 'auto',
		width: '50%',
		transition: '1.2s',
		right: '0',
		paddingBottom: '1px',
		top: '45px',
		marginTop: '0px',
		zIndex: '90',
		bottom: '-1px',
	},
	filter_drawer: {
		zIndex: '101 !important',
		width: '35%',
	},
	drawer_content: {
		position: 'relative',
		width: '100%',
		height: '100%',
		backgroundColor: ({ theme }: any) => {
			return `${theme.colors.quickViewDrawBackground} !important`;
		},
		overflow: 'hidden',
		padding: '0',
		zIndex: '1000',
		boxShadow: '0px 1px 10px 0px rgba(0, 0, 0, 0.25)',
		WebkitOverflowScrolling: 'touch',
	},
	page_header_title: {
		color: ({ theme }: any) => theme.colors.black,
		paddingLeft: '1rem',
		display: 'flex',
		justifyContent: 'space-between',
		alignItems: 'center',
	},
	page_header_hldr: {
		paddingLeft: '1rem',
		textOverflow: 'ellipsis',
		whiteSpace: 'nowrap',
		flexShrink: 0,
		width: 'auto' /* 152px */,
		height: 48,
		display: 'flex',
		flexDirection: 'row',
		justifyContent: 'center',
		alignItems: 'center',
		overflow: 'visible',
	},
	multiple_page_header_operations: {
		padding: '0',
		width: '47%',
		marginTop: 'unset !important',
		display: 'flex',
		alignItems: 'center',
	},
	page_header_operations: {
		padding: '0',
		marginTop: 'unset !important',
		display: 'flex',
		alignItems: 'center',
	},
	button_container: {
		marginLeft: 'auto',
		display: 'flex',
	},
	page_header_operations_button: {
		marginRight: '16px',
	},
	operations: {},
	drawer_operations: {},
	qvexpand: {
		display: 'block',
		paddingLeft: '13px',
		minWidth: '50px',
		width: '50px',
		position: 'absolute',
		borderRadius: '0',
		fontWeight: '700',
		left: '1rem',
		bottom: '1rem',
		background: '0 0',
		border: 'none !important',
		boxShadow: 'none',
	},
	qv_btn: {
		color: ({ theme }: any) => theme.colorScales.colorDarkGray,
		background: ({ theme }: any) => theme.colorScales.colorLightGray,
	},
	fixed_page_content: {
		marginLeft: '0',
		marginRight: '0',
		overflow: 'auto',
		paddingBottom: '30px',
		height: 'calc(100% - 3rem)',
		overflowY: 'visible',
		overflowX: 'hidden',
		position: 'relative',
		top: '0px',
	},
	page_header_text: {
		padding: '0px 16px',
		display: 'inline-block',
		flexShrink: 0,
		width: 'auto',
		height: 'auto',
		whiteSpace: 'pre',
		overflow: 'visible',
		fontWeight: 600,
		fontStyle: 'normal',
		fontFamily: '"Nunito Sans", sans-serif',
		color: ({ theme }: any) => theme.colors.quickViewPageColor,
		fontSize: 18,
		letterSpacing: -0.2,
		lineHeight: 1.2,
		textAlign: 'left',
		margin: '0px',
		marginBottom: '0px',
	},
	fixed_page_header_title: {
		paddingRight: '15px',
		position: 'relative',
		zIndex: '8',
		marginBottom: '0',
		cursor: 'default',
		left: '0',
		right: '0',
		color: ({ theme }: any) => theme.colors.colorNeutral9,
		borderBottom: 'solid 1px',
		borderBottomColor: ({ theme }: any) => theme.colors.inputBorderColor,
		boxSizing: 'border-box',
		flexShrink: 0,
		width: '100%',
		height: 'auto' /* 64px */,
		display: 'flex',
		flexDirection: 'row',
		justifyContent: 'space-between',
		alignItems: 'center',
		padding: '14px 16px',
		backgroundColor: ({ theme }: any) => theme.colors.quickViewDrawBackground,
		overflow: 'visible',
		borderColor: ({ theme }: any) => theme.colors.inputBorderColor,
	},
	qvclose: {
		flexShrink: 0,
		width: 36,
		height: 36,
		backgroundColor: ({ theme }: any) => theme.colors.gigaGrey1,
		overflow: 'visible',
		borderRadius: 8,
		display: 'inline-block',
		padding: '10px',
		minWidth: '36px',
		border: 'none !important',
		fontWeight: '600',
	},
	btn_outline_secondary: {
		color: ({ theme }: any) => theme.colors.gigaGrey1,
	},
});

export default QuickViewStyles;
