import { createUseStyles } from 'react-jss';

const SplitViewStyles = createUseStyles((theme: any) => ({
	container: {
		width: '100%',
		display: 'flex',
		flexDirection: 'column',
		backgroundColor: theme.colors.white,
		borderColor: theme.colors.solitude,
		borderStyle: 'solid',
		borderTopWidth: 1,
		borderBottomWidth: 0,
		borderLeftWidth: 0,
		borderRightWidth: 0,
	},
	header: {
		flexShrink: 0,
		height: 64,
		display: 'flex',
		justifyContent: 'space-between',
		padding: '8px 16px',
		backgroundColor: theme.colors.quickViewDrawBackground,
		position: 'relative',
		alignContent: 'center',
		borderColor: theme.colors.solitude,
		borderStyle: 'solid',
		borderTopWidth: 0,
		borderBottomWidth: 1,
		borderLeftWidth: 0,
		borderRightWidth: 0,
	},
	headerContent: {
		width: 'calc(100% - 200px)',
		height: '100%',
		display: 'flex',
		overflow: 'visible',
		position: 'relative',
		padding: '0px',
		gap: 8,
	},
	titleHeaderContent: {
		alignItems: 'center',
		maxWidth: '30%',
		display: 'flex',
		gap: 8,
	},
	closeIcon: {
		width: 36,
		height: 36,
		backgroundColor: theme.colors.scrollBarColor,
		borderRadius: 8,
		flexShrink: 0,
	},
	resizeIcon: {
		width: 36,
		height: 36,
		display: 'flex',
		justifyContent: 'center',
		alignItems: 'center',
		backgroundColor: theme.colors.scrollBarColor,
		alignContent: 'center',
		borderRadius: 8,
	},
	titleHeaderCaption: {
		flexShrink: 0,
		width: 'auto',
		height: 'auto',
		fontWeight: 800,
		color: theme.colors.splitviewHeaderGrey,
		fontSize: 20,
	},
	titleHeader: {
		flexShrink: 0,
		width: 'auto',
		height: 'auto',
		fontWeight: 400,
		color: theme.colors.splitviewHeaderGrey,
		fontSize: 20,
		overflow: 'hidden',
		whiteSpace: 'nowrap',
		textOverflow: 'ellipsis',
		maxWidth: 'calc(100% - 50px)',
	},
	tabSection: {
		width: '70%',
		display: 'flex',
		alignItems: 'center',
		padding: '5px 8px 5px 64px',
		alignContent: 'center',
		gap: 64,
	},
	tabButton: {
		width: 'min-content',
		height: 35,
		display: 'flex',
		justifyContent: 'flex-start',
		alignItems: 'center',
		padding: '0px 12px',
		alignContent: 'center',
		gap: 10,
		borderRadius: 6,
		flexShrink: 0,
		fontWeight: 800,
		color: theme.colors.lightGreen,
		fontSize: 16,
		lineHeight: 1,
		textAlign: 'center',
		background: 'transparent',
		border: 1,
		'&:hover': {
			backgroundColor: theme.colors.scrollBarColor,
			color: theme.colors.splitviewHeaderGrey,
		},
	},
	activeTabButton: {
		width: 'min-content',
		height: 35,
		display: 'flex',
		padding: '2px 12px',
		backgroundColor: theme.colors.lightGreen,
		gap: 10,
		borderRadius: 6,
		fontWeight: 800,
		color: theme.colors.white,
		fontSize: 16,
		lineHeight: 1,
		border: 1,
		alignItems: 'center',
		'&:hover': {
			backgroundColor: `${theme.colors.splitviewHOverGrey} !important`,
			height: '35px !important',
			borderRadius: '6px !important',
			padding: '2px 12px !important',
			width: 'min-content !important',
		},
	},
	headerOption: {
		alignItems: 'center',
		display: 'flex',
		gap: 16,
	},
	splitviewBody: {
		flex: '1 0 0px',
		paddingTop: 8,
		gap: 16,
		overflow: 'auto',
	},
	nav: {
		marginBottom: 20,
		minWidth: 300,
		maxWidth: 400,
	},
	li: {
		display: 'inline-block',
		position: 'relative',
	},
	hidden: {
		display: 'none',
	},
	subul: {
		position: 'absolute',
		top: '100%',
		right: '0',
		marginRight: '0',
		display: 'none',
	},
	subli: {
		marginTop: 1,
	},
	noStyleList: {
		'list-style-type': 'none',
	},
}));

export default SplitViewStyles;
